name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Or your preferred Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build and export the Next.js static site
      - name: Build and export static files
        run: |
          npm run build
          npm run export

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use your secret token here
        run: |
          # Configure Git for deployment
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add remote with access token
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/augustinejoseph/augustinejoseph.github.io.git

          # Create a new branch and switch to it
          git checkout --orphan gh-pages

          # Remove all files from the index (because it's a new branch)
          git rm -rf .

          # Copy the exported static files to the root of the repository
          cp -a out/. .

          # Add and commit the changes
          git add -A
          git commit -m "Deploy to GitHub Pages"

          # Force push the changes to the gh-pages branch
          git push --force origin gh-pages

